branches:
  only:
    - master

language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.24.1

before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# as the deployment to AWS with Travis is not required (https://knowledge.udacity.com/questions/106089) and i would not
# want to have my actual secret yaml files committed to github, the following lines are commented out.
#  - mkdir ${HOME}/.kube
#  - cp course-03/exercises/udacity-c3-deployment/kubeone-terraform/udagram-kubeconfig ${HOME}/.kube/config
#  - kubectl config set clusters.k8s.local.certificate-authority-data "$KUBE_CLUSTER_CERTIFICATE"
#  - kubectl config set users.k8s.local.client-certificate-data "$KUBE_CLIENT_CERTIFICATE"
#  - kubectl config set users.k8s.local.client-key-data "$KUBE_CLIENT_KEY"

install:
  - docker-compose -f course-03/exercises/udacity-c3-deployment/docker/docker-compose-build.yaml build --parallel
  - docker-compose -f course-03/exercises/udacity-c3-deployment/docker/docker-compose-build.yaml push
#  - kubectl apply -f course-03/exercises/udacity-c3-deployment/k8s/config-maps-and-secrets/aws-secret.yaml
#  - kubectl apply -f course-03/exercises/udacity-c3-deployment/k8s/config-maps-and-secrets/env-configmap.yaml
#  - kubectl apply -f course-03/exercises/udacity-c3-deployment/k8s/config-maps-and-secrets/env-secret.yaml
#  - kubectl apply -f course-03/exercises/udacity-c3-deployment/k8s/backend-feed-deployment.yaml
#  - kubectl apply -f course-03/exercises/udacity-c3-deployment/k8s/backend-feed-service.yaml
#  - kubectl apply -f course-03/exercises/udacity-c3-deployment/k8s/backend-user-deployment.yaml
#  - kubectl apply -f course-03/exercises/udacity-c3-deployment/k8s/backend-user-service.yaml
#  - kubectl apply -f course-03/exercises/udacity-c3-deployment/k8s/frontend-deployment.yaml
#  - kubectl apply -f course-03/exercises/udacity-c3-deployment/k8s/frontend-service.yaml
#  - kubectl apply -f course-03/exercises/udacity-c3-deployment/k8s/reverseproxy-deployment.yaml
#  - kubectl apply -f course-03/exercises/udacity-c3-deployment/k8s/reverseproxy-service.yaml
