apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: modul1/udacity-restapi-user
        name: backend-user
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: USER_MS_PORT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: USER_MS_PORT
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: JWT_SECRET
        - name: USER_MS_POSTGRESS_DB
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: USER_MS_POSTGRESS_DB
        - name: USER_MS_POSTGRESS_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: USER_MS_POSTGRESS_HOST
        - name: USER_MS_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: USER_MS_POSTGRES_PASSWORD
        - name: USER_MS_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: USER_MS_POSTGRES_USERNAME
      restartPolicy: Always


