version: "3"
services:
  reverseproxy:
    build:
      context: ../../udacity-c3-reverse-proxy
    image: modul1/reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: modul1/udacity-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed
    image: modul1/udacity-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend
    image: modul1/udacity-frontend:local
